export const DELETE_COVER_LETTER = 'DELETE_COVER_LETTER';
export const CREATE_COVER_LETTER = 'CREATE_COVER_LETTER';
export const VIEW_COVER_LETTER = 'VIEW_COVER_LETTER';
export const CREATE_JOB_POSTING = 'CREATE_JOB_POSTING';
export const RETURN_TO_MAIN_PAGE = 'RETURN_TO_MAIN_PAGE';
