export const DELETE_COVER_LETTER = 'DELETE_COVER_LETTER';
export const CREATE_COVER_LETTER = 'CREATE_COVER_LETTER';
export const VIEW_COVER_LETTER = 'VIEW_COVER_LETTER';
export const CREATE_JOB_POSTING = 'CREATE_JOB_POSTING';
export const RETURN_TO_MAIN_PAGE = 'RETURN_TO_MAIN_PAGE';
export const LANGUAGES = [
  'javascript',
  'react',
  'angular',
  'html',
  'css',
  'framework',
  'frameworks',
  'jqurey',
  'object',
  'functional',
  'develop',
  'python',
  'c',
  'typescript',
  'rust',
  'java',
  'php',
  'swift',
  'sql',
  'mysql',
  'nosql',
  'ruby',
  'net',
  'test',
  'tdd',
  'node',
  'algorithm',
  'array',
  'boolean',
  'variable',
  'program',
  'argument',
  'ascii',
  'bug',
  'code',
  'conditional',
  'data',
  'loop',
  'pointer',
  'language',
  'backend',
  'frontend',
  'server',
  'syntax',
  'go',
  'sass',
  'cobol',
  'kotlin',
  'android',
  'apple',
  'visual',
  'office',
  'git',
  'bash',
  'gitbash',
  'github',
];
